# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none # will disable CI builds entirely
pr: none # will disable PR builds entirely; will not disable CI triggers


pool:
  vmImage: 'ubuntu-latest'

- script: |
    RUN cd Open3D && mkdir build && cd build \
    && cmake -DENABLE_HEADLESS_RENDERING=ON -DENABLE_GUI=OFF -DBUILD_GLEW=ON -DBUILD_GLFW=ON .. \
    && make -j$(nproc) 
  displayName: 'Build Open3D'
