# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none # will disable CI builds entirely
pr: none # will disable PR builds entirely; will not disable CI triggers


pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    sudo apt-get install -y python3-pip python3-dev 
  displayName: 'python3-dev'

- task: ShellScript@2
  inputs:
    scriptPath: util/install_deps_ubuntu.sh

- script: |
    mkdir build && cd build \
    && cmake -DENABLE_HEADLESS_RENDERING=ON -DENABLE_GUI=OFF -DBUILD_GLEW=ON -DBUILD_GLFW=ON .. \
    && make -j$(nproc) 
  displayName: 'Build Open3D'

- script: |
    ls build
  displayName: 'list build'